algorithm_type: GradientBoostingClassifier
evaluation_params:
  metrics_output_path: D:\MADE_homeworks\ML_prod\homework1_repo\ml_project\ml_project\reports\GB_metrics.json
  scorer_collection:
  - accuracy_score
  - precision_score
  - recall_score
  - average_precision_score
  - roc_auc_score
feature_params:
  target_col: target
  categorical_features:
    - 'cp'
    - 'restecg'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  selected_features:
    - 'cp'
    - 'trestbps'
    - 'restecg'
input_data_path: D:\MADE_homeworks\ML_prod\homework1_repo\ml_project\ml_project\data\raw\heart.csv
output_model_path: D:\MADE_homeworks\ML_prod\homework1_repo\ml_project\ml_project\models\model_output_GB.pkl
splitting_params:
  test_size: 0.2
train_params:
  model_factory: GradientBoostingClassifier
  model_hyperparams:
    n_estimators: 250
    learning_rate: 0.01
    max_depth: 3
