algorithm_type: LogisticRegression
evaluation_params:
  metrics_output_path: reports\baseline.json
  scorer_collection:
  - accuracy_score
  - precision_score
  - recall_score
  - average_precision_score
  - roc_auc_score
feature_params:
  target_col: target
  categorical_features:
    - 'cp'
    - 'restecg'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  selected_features:
    - 'cp'
    - 'trestbps'
    - 'restecg'
input_data_path: data\raw\heart.csv
output_model_path: models\model_output_baseline.pkl
splitting_params:
  test_size: 0.2
train_params:
  model_factory: LogisticRegression
  model_hyperparams:
    C: 0.0001
