algorithm_type: RandomForestClassifier
evaluation_params:
  metrics_output_path: reports\RF_metrics.json
  scorer_collection:
  - accuracy_score
  - precision_score
  - recall_score
  - average_precision_score
  - roc_auc_score
feature_params:
  target_col: target
  categorical_features:
    - 'cp'
    - 'restecg'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  selected_features:
    - 'cp'
    - 'trestbps'
    - 'restecg'
input_data_path: data\raw\heart.csv
output_model_path: models\model_RF.pkl
splitting_params:
  test_size: 0.2
  shuffle: True
train_params:
  model_factory: RandomForestClassifier
  model_hyperparams:
    n_estimators: 120
    min_samples_leaf: 5
